language: c

jobs:
  include:
    ### 64-bit build on AMD64 ###
    - os: linux
      dist: focal
      env: BADGE=linux
      compiler: gcc-10
      addons:
        apt:
          sources: ["ubuntu-toolchain-r-test"]
          packages: ["gcc-10", "libusb-1.0.0-dev", "libgtk-3-dev", "rpm"]

    ### 32-bit build on AMD64 ###
    - os: linux
      dist: focal
      env: BADGE=linux
      compiler: gcc-10
      addons:
        apt:
          sources: ["ubuntu-toolchain-r-test"]
          packages: ["gcc-10", "libusb-1.0.0-dev", "libgtk-3-dev", "rpm"]
      before_install:
        - CFLAGS="$CFLAGS -m32"; CXXFLAGS="$CXXFLAGS -m32"; LDFLAGS="$LDFLAGS -m32";

    ### cross build on AMD64 ###
    - os: linux
      dist: focal
      env: BADGE=linux-mingw
      name: linux-mingw
      compiler: gcc-10
      addons:
        apt:
          sources: ["ubuntu-toolchain-r-test"]
          packages:
            ["gcc-10", "libusb-1.0.0-dev", "libgtk-3-dev", "rpm", "mingw-w64"]
      before_install:
        - LDFLAGS="$LDFLAGS -NDEBUG";

    ### macOS ###
    # - os: osx
    #   env: BADGE=osx
    #   osx_image: xcode11.3
    #   name: macOS 10.14.6 gcc
    #   compiler: gcc
    #   addons:
    #     homebrew:
    #       packages:
    #         - gcc
    #         - libusb
    #         - gtk+3

    # - os: osx
    #   env: BADGE=osx
    #   osx_image: xcode11.3
    #   name: macOS 10.14.6 gcc 32-bit
    #   compiler: gcc
    #   addons:
    #     homebrew:
    #       packages:
    #         - gcc
    #         - libusb
    #         - gtk+3
    #   before_install:
    #     - CFLAGS="$CFLAGS -m32"; CXXFLAGS="$CXXFLAGS -m32"; LDFLAGS="$LDFLAGS -m32";

    # - os: osx
    #   env: BADGE=osx
    #   osx_image: xcode11.3
    #   name: macOS 10.14.6 clang
    #   compiler: clang
    #   addons:
    #     homebrew:
    #       packages:
    #         - llvm
    #         - libusb
    #         - gtk+3

    # - os: osx
    #   env: BADGE=osx
    #   osx_image: xcode11.3
    #   name: macOS 10.14.6 clang 32-bit
    #   compiler: clang
    #   addons:
    #     homebrew:
    #       packages:
    #         - llvm
    #         - libusb
    #         - gtk+3
    #   before_install:
    #     - CFLAGS="$CFLAGS -m32"; CXXFLAGS="$CXXFLAGS -m32"; LDFLAGS="$LDFLAGS -m32";

script:
  - git fetch --tags
  - printenv
  - cmake --version
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] || [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./.travis.sh; fi
