name: C/C++ CI

on:
  push:
    branches: [develop, testing]
  pull_request:
    branches: [develop, testing]

jobs:
  job_linux_1a:
    name: ubuntu-20.04 gcc
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get install gcc-10 libusb-1.0.0-dev libgtk-3-dev rpm
      - name: make debug
        run: make debug
      - name: make test
        run: make test
      - name: make release
        run: make release
      - name: make install
        run: make install
      - name: make package
        run: make package
      - name: make uninstall
        run: make uninstall
      - name: make clean
        run: make clean

  job_linux_2a:
    name: ubuntu-18.04 gcc
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: sudo apt-get install gcc-6 libusb-1.0.0-dev libgtk-3-dev rpm
      - name: make debug
        run: make debug
      - name: make test
        run: make test
      - name: make release
        run: make release
      - name: make install
        run: make install
      - name: make package
        run: make package
      - name: make uninstall
        run: make uninstall
      - name: make clean
        run: make clean

  job_linux_3a:
    name: ubuntu-16.04 gcc
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get install gcc-5 libusb-1.0.0-dev libgtk-3-dev rpm
      - name: make debug
        run: make debug
      - name: make test
        run: make test
      - name: make release
        run: make release
      - name: make install
        run: make install
      - name: make package
        run: make package
      - name: make uninstall
        run: make uninstall
      - name: make clean
        run: make clean

  job_linux_1b:
    name: ubuntu-20.04 clang
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get install clang-10 libusb-1.0.0-dev libgtk-3-dev rpm
      - name: make debug
        run: make debug
      - name: make test
        run: make test
      - name: make release
        run: make release
      - name: make install
        run: make install
      - name: make package
        run: make package
      - name: make uninstall
        run: make uninstall
      - name: make clean
        run: make clean

  job_linux_2b:
    name: ubuntu-18.04 clang
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: sudo apt-get install clang-10 libusb-1.0.0-dev libgtk-3-dev rpm
      - name: make debug
        run: make debug
      - name: make test
        run: make test
      - name: make release
        run: make release
      - name: make install
        run: make install
      - name: make package
        run: make package
      - name: make uninstall
        run: make uninstall
      - name: make clean
        run: make clean

  job_linux_3b:
    name: ubuntu-16.04 clang
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get install clang libusb-1.0.0-dev libgtk-3-dev rpm
      - name: make debug
        run: make debug
      - name: make test
        run: make test
      - name: make release
        run: make release
      - name: make install
        run: make install
      - name: make package
        run: make package
      - name: make uninstall
        run: make uninstall
      - name: make clean
        run: make clean

  job_linux_1c:
    name: ubuntu-20.04 gcc 32-bit
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get install gcc-10 libusb-1.0.0-dev libgtk-3-dev rpm
      - name: Set compiler flags
        run: |
          CFLAGS="$CFLAGS -m32"
          CXXFLAGS="$CXXFLAGS -m32"
          LDFLAGS="$LDFLAGS -m32"
      - name: make debug
        run: make debug
      - name: make test
        run: make test
      - name: make release
        run: make release
      - name: make install
        run: make install
      - name: make package
        run: make package
      - name: make uninstall
        run: make uninstall
      - name: make clean
        run: make clean

  job_linux_2c:
    name: ubuntu-18.04 gcc 32-bit
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: sudo apt-get install gcc-6 libusb-1.0.0-dev libgtk-3-dev rpm
      - name: Set compiler flags
        run: |
          CFLAGS="$CFLAGS -m32"
          CXXFLAGS="$CXXFLAGS -m32"
          LDFLAGS="$LDFLAGS -m32"
      - name: make debug
        run: make debug
      - name: make test
        run: make test
      - name: make release
        run: make release
      - name: make install
        run: make install
      - name: make package
        run: make package
      - name: make uninstall
        run: make uninstall
      - name: make clean
        run: make clean

  job_linux_3c:
    name: ubuntu-16.04 gcc 32-bit
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get install gcc-5 libusb-1.0.0-dev libgtk-3-dev rpm
      - name: Set compiler flags
        run: |
          CFLAGS="$CFLAGS -m32"
          CXXFLAGS="$CXXFLAGS -m32"
          LDFLAGS="$LDFLAGS -m32"
      - name: make debug
        run: make debug
      - name: make test
        run: make test
      - name: make release
        run: make release
      - name: make install
        run: make install
      - name: make package
        run: make package
      - name: make uninstall
        run: make uninstall
      - name: make clean
        run: make clean

  job_linux_4:
    name: ubuntu-20.04 mingw64
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get install gcc-10 libusb-1.0.0-dev libgtk-3-dev rpm mingw-w64
      - name: make debug
        run: make debug
      - name: make test
        run: make test
      - name: make release
        run: make release
      - name: make install
        run: make install
      - name: make package
        run: make package
      - name: make uninstall
        run: make uninstall
      - name: make clean
        run: make clean

  # job_macos_1a:
  #   name: macos-11.0 gcc
  #   runs-on: macos-11.0
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Install dependencies
  #       run: brew install gcc libusb gtk+3
  #     - name: make debug
  #       run: make debug
  #     - name: make test
  #       run: make test
  #     - name: make release
  #       run: make release
  #     - name: make install
  #       run: make install
  #     - name: make package
  #       run: make package
  #     - name: make uninstall
  #       run: make uninstall
  #     - name: make clean
  #       run: make clean

  job_macos_2a:
    name: macos-10.15 gcc
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: brew install gcc libusb gtk+3
      - name: make debug
        run: make debug
      - name: make test
        run: make test
      - name: make release
        run: make release
      - name: make install
        run: make install
      - name: make package
        run: make package
      - name: make uninstall
        run: make uninstall
      - name: make clean
        run: make clean

  # job_macos_1b:
  #   name: macos-11.0 clang
  #   runs-on: macos-11.0
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Install dependencies
  #       run: brew install llvm libusb gtk+3
  #     - name: make debug
  #       run: make debug
  #     - name: make test
  #       run: make test
  #     - name: make release
  #       run: make release
  #     - name: make install
  #       run: make install
  #     - name: make package
  #       run: make package
  #     - name: make uninstall
  #       run: make uninstall
  #     - name: make clean
  #       run: make clean

  job_macos_2b:
    name: macos-10.15 clang
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: brew install llvm libusb gtk+3
      - name: make debug
        run: make debug
      - name: make test
        run: make test
      - name: make release
        run: make release
      - name: make install
        run: make install
      - name: make package
        run: make package
      - name: make uninstall
        run: make uninstall
      - name: make clean
        run: make clean
